### PR TITLE
Adds total spectra extraction

### PR DESCRIPTION
**Pull request by ackagel**
Adds total spectra extraction.  This will help validate that ionpath's default mass calibration parameters are within tolerance.

### CODE REVIEW

**Review by ngreenwald — CHANGES_REQUESTED** [review]
Still failing

**Comment by alex-l-kong** [comment]
Do we plan on further developing this PR? If so, I can take over.

**Comment by ngreenwald** [comment]
I think @jranek maybe needed something similar, and Avery might have gone to office hours for something related? If no one needs it though, fine to close this branch

**Comment by alex-l-kong** [comment]
@jranek just wanted to get some ideas from you regarding this setup. Adam used a slightly different setup to start off with. I modified it so instead of taking the total mass spectra across all pixels, it would delineate the spectra across individual pixels.

**Review by jranek — CHANGES_REQUESTED** [review]
Hey @alex-l-kong, I went to test these files to see if it gives a per-pixel spectra output; however, it immediately crashes due to memory error regardless of (1) the bin file size, (2) the number of FOVs I pass through, or (3) the spectra range specified in the panel df

**Comment by jranek** [comment]
@alex-l-kong this looks great!! As a suggestion, I think it's worth converting the tof ranges back to m/z for ease of plotting the spectra. For example, 

```python
def _tof2mass(tof_range: np.ndarray, mass_offset: float, mass_gain: float,
              time_res: float) -> np.ndarray:
    """Convert array of time of flight values to equivalent m/z

    Args:
        toff_arr (array_like):
            Array of time of flight values
        mass_offset (float):
            Mass offset for parabolic transformation
        mass_gain (float):
            Mass gain for parabolic transformation
        time_res (float):
            Time resolution for scaling parabolic transformation

    Returns:
        array_like:
            Array of m/z values; indicies paried to `toff_arr`
    """
    return (((time_res * tof_range) - mass_offset) / mass_gain)**2
```
The mass range interval can be in the return statement or appended as metadata in the `fov_files` dictionary. Also, it might be worth renaming `fov_files` in the return to be a little more descriptive of the metadata within the dictionary, or just providing a little more detail in the docstring!

**Comment by alex-l-kong** [comment]
> @alex-l-kong this looks great!! As a suggestion, I think it's worth converting the tof ranges back to m/z for ease of plotting the spectra. For example,
> 
> ```python
> def _tof2mass(tof_range: np.ndarray, mass_offset: float, mass_gain: float,
>               time_res: float) -> np.ndarray:
>     """Convert array of time of flight values to equivalent m/z
> 
>     Args:
>         toff_arr (array_like):
>             Array of time of flight values
>         mass_offset (float):
>             Mass offset for parabolic transformation
>         mass_gain (float):
>             Mass gain for parabolic transformation
>         time_res (float):
>             Time resolution for scaling parabolic transformation
> 
>     Returns:
>         array_like:
>             Array of m/z values; indicies paried to `toff_arr`
>     """
>     return (((time_res * tof_range) - mass_offset) / mass_gain)**2
> ```
> 
> The mass range interval can be in the return statement or appended as metadata in the `fov_files` dictionary. Also, it might be worth renaming `fov_files` in the return to be a little more descriptive of the metadata within the dictionary, or just providing a little more detail in the docstring!

Changes are added. Lmk how this new version looks @jranek.

**Review by jranek — APPROVED** [review]
Looks awesome!!

**Pull request merged**
