### PR TITLE
Bug 32 numpy conflicts

### PR DESCRIPTION
**Pull request by ackagel**
## **Purpose**

closes issue #32 

## **Implementation**

Uses oldest supported numpy metapackage for building.  According to the [numpy docs](https://numpy.org/devdocs/user/depending_on_numpy.html#build-time-dependency), this is the most consistent way to avoid conflicting numpy versions.

## **Remaining issues**

Not a big fan about how dependent we are on a metapackage for dealing with numpy conflicts, but that's more of a personal gripe than anything serious.

### CODE REVIEW

**Comment by ngreenwald** [comment]
Is there a reason that these old PRs keep added as changes to dev?

Do we need to merge main into dev separately?

**Comment by ngreenwald** [comment]
image

**Comment by ackagel** [comment]
last one should've been merged to main from dev, my b.  The pr->dev->main just makes sure I bump the version in setup.py and make it a tagged release

**Comment by ngreenwald** [comment]
Right, but #24 and #28 are already merged into main, so why are they showing up in the change log here?

**Comment by ackagel** [comment]
I think those where directly merged into main, but weren't merged into dev first. since this is being merged into dev first, they're showing up here in the change log, since those changes aren't currently in dev

**Comment by ngreenwald** [comment]
Got it

**Review by ngreenwald — APPROVED** [review]

**Pull request merged**
